# Generated by Django 5.0 on 2025-07-10 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, help_text='WhatsApp phone number in international format (e.g., +1234567890)', max_length=50, null=True, unique=True)),
                ('phone_number_id', models.CharField(blank=True, help_text='WhatsApp phone number ID', max_length=255, null=True, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('disconnected', 'Disconnected')], default='draft', max_length=50)),
                ('whatsapp_connected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_updated'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='WhatsAppBusinessAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_id', models.CharField(blank=True, help_text='WABA Business ID from Meta', max_length=255, null=True)),
                ('business_name', models.CharField(blank=True, help_text='WABA Business Name from Meta', max_length=128, null=True)),
                ('access_token', models.TextField(blank=True, help_text='WABA Business Access Token from Meta', null=True)),
                ('phone_number_id', models.CharField(blank=True, help_text='WhatsApp Phone Number ID from Meta', max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, help_text='WhatsApp phone number in international format (e.g., +1234567890)', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bot', models.OneToOneField(help_text='The bot this WABA is connected to.', on_delete=django.db.models.deletion.CASCADE, related_name='waba', to='bots.bot')),
                ('user', models.ForeignKey(help_text='The user who owns this WABA.', on_delete=django.db.models.deletion.CASCADE, related_name='wabas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'business_id', 'phone_number_id')},
            },
        ),
    ]
