# Generated by Django 5.2.2 on 2025-06-12 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='phone_number',
            field=models.CharField(default=123434432, help_text='WhatsApp phone number in international format (e.g., +1234567890)', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
