# Generated by Django 5.2.2 on 2025-06-12 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_bot_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='phone_number',
            field=models.CharField(blank=True, help_text='WhatsApp phone number in international format (e.g., +1234567890)', max_length=20, null=True, unique=True),
        ),
    ]
