# Generated by Django 5.0 on 2025-07-10 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_bot_notification_settings_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('bot_online', 'Bot Online'), ('bot_offline', 'Bot Offline'), ('new_message', 'New Message'), ('message_failure', 'Message Failure'), ('new_chat', 'New Chat'), ('whatsapp_connected', 'WhatsApp Connected'), ('whatsapp_disconnected', 'WhatsApp Disconnected'), ('bot_created', 'Bot Created'), ('bot_deleted', 'Bot Deleted'), ('bot_duplicated', 'Bot Duplicated'), ('flow_published', 'Flow Published'), ('flow_archived', 'Flow Archived')], max_length=32),
        ),
    ]
