# Generated by Django 5.0 on 2025-06-21 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0003_alter_bot_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='phone_number_id',
            field=models.CharField(blank=True, help_text='WhatsApp phone number ID', max_length=255, null=True, unique=True),
        ),
    ]
