# Generated by Django 5.0 on 2025-07-20 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0004_notificationsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationsettings',
            name='event_preferences',
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='bot_activity',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='bot_online_offline',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='failed_delivery',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='in_app_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='marketing_emails',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='new_chat_started',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='new_messages',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='platform_updates',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='sms_notifications',
            field=models.BooleanField(default=False),
        ),
    ]
