# Generated by Django 5.0 on 2025-06-21 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0004_bot_phone_number_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='flow_data',
        ),
    ]
