services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - wozza-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    environment:
      DEBUG: ${DEBUG:-False}
      GUNICORN_WORKERS: ${GUNICORN_WORKERS:-3}
      GUNICORN_TIMEOUT: ${GUNICORN_TIMEOUT:-120}
    volumes:
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
      - ./logs:/app/logs/
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "127.0.0.1:8000:8000"
    restart: unless-stopped
    networks:
      - wozza-network

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    environment:
      DEBUG: ${DEBUG:-True}
    command: celery -A API worker -l info
    working_dir: /app
    volumes:
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
      - ./logs:/app/logs/
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - wozza-network

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    environment:
      DEBUG: ${DEBUG:-False}
    command: celery -A API beat -l info
    working_dir: /app
    volumes:
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
      - ./logs:/app/logs/
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - wozza-network

networks:
  wozza-network:
    name: wozza-network
    driver: bridge