# Generated by Django 5.0 on 2025-08-01 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0005_remove_notificationsettings_event_preferences_and_more'),
        ('subscription', '0003_alter_subscription_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('google', 'Google')], max_length=20)),
                ('display_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('cost_per_1k_tokens', models.DecimalField(decimal_places=6, max_digits=10)),
                ('credit_conversion_rate', models.DecimalField(decimal_places=6, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['provider', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CreditUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_tokens', models.IntegerField()),
                ('output_tokens', models.IntegerField()),
                ('cost_usd', models.DecimalField(decimal_places=6, max_digits=10)),
                ('credits_deducted', models.DecimalField(decimal_places=6, max_digits=10)),
                ('request_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_usage_logs', to='bots.bot')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='subscription.aimodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_usage_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserCreditBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits_remaining', models.IntegerField(default=0)),
                ('credits_used_this_period', models.IntegerField(default=0)),
                ('credits_reset_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_balance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
