# Generated by Django 5.0 on 2025-08-01 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_aimodel_creditusagelog_usercreditbalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='credits_per_month',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='features',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
