# Generated by Django 5.0 on 2025-08-01 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_subscriptionplan_credits_per_month_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='features',
        ),
    ]
