# Generated by Django 5.0 on 2025-08-03 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0006_remove_subscriptionplan_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='is_trial_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='trial_credits_allocated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usercreditbalance',
            name='is_trial_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usercreditbalance',
            name='trial_credits_allocated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
