# Generated by Django 5.0 on 2025-08-11 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0009_alter_subscription_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='plan_type',
            field=models.CharField(choices=[('starter', 'Starter'), ('growth', 'Growth'), ('scale', 'Scale')], max_length=20),
        ),
    ]
