NOTIFICATION_EVENT_TYPES = {
    "bot_online": "Bot Online",
    "bot_offline": "Bot Offline",
    "whatsapp_connected": "WhatsApp Connected",
    "whatsapp_disconnected": "WhatsApp Disconnected",
    "bot_paused": "Bot Paused",
    "bot_resumed": "Bot Resumed",
    "flow_published": "Flow Published",
    "flow_archived": "Flow Archived",
    "new_message": "New Customer Message",
    "new_chat": "New Chat Started",
    "message_failure": "Message Delivery Failure",
    "agent_handoff": "Agent Handoff Activated",
    "agent_reply": "Agent Reply Sent",
    "subscription_activated": "Subscription Activated",
    "payment_success": "Payment Successful",
    "payment_failed": "Payment Failed",
    "trial_ending": "Trial Ending Soon",
    "password_change": "Password Changed",
    "account_deletion_requested": "Account Deletion Requested",
    "profile_update": "Profile Updated",
    "export_data_ready": "Export Data Ready",
    "security_alert": "Security Alert",
    "unread_message_summary": "Unread Message Summary",
    # Add new types here as needed
} 