# Generated by Django 5.0 on 2025-07-10 16:21

import django.db.models.deletion
import flows.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('flow_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flows', to='bots.bot')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('bot', 'name')},
            },
        ),
        migrations.CreateModel(
            name='GoogleDocCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(unique=True)),
                ('last_hash', models.CharField(blank=True, max_length=128, null=True)),
                ('last_fetched', models.DateTimeField(auto_now=True)),
                ('node_id', models.CharField(blank=True, max_length=255, null=True)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gdoc_caches', to='flows.flow')),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(blank=True, help_text='The ID of the node within the flow this file belongs to.', max_length=255, null=True)),
                ('name', models.CharField(help_text='Original name of the file.', max_length=255)),
                ('file', models.FileField(upload_to=flows.models.flow_directory_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='flows.flow')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
