# Generated by Django 5.0 on 2025-07-15 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0003_alter_notification_type'),
        ('flows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('user_id', models.CharField(db_index=True, max_length=255)),
                ('handoff_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='bots.bot')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('bot', 'conversation_id')},
            },
        ),
    ]
