# Generated by Django 5.0 on 2025-06-21 07:20

import django.db.models.deletion
import flows.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Original name of the file.', max_length=255)),
                ('file', models.FileField(upload_to=flows.models.flow_directory_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='flows.flow')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
