# Generated by Django 5.0 on 2025-06-21 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0002_uploadedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='node_id',
            field=models.CharField(blank=True, help_text='The ID of the node within the flow this file belongs to.', max_length=255, null=True),
        ),
    ]
