# Generated by Django 5.0 on 2025-07-30 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0003_googleoauthtoken_googleuserfile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='googleoauthtoken',
            options={'verbose_name': 'Google OAuth Token', 'verbose_name_plural': 'Google OAuth Tokens'},
        ),
        migrations.AlterModelOptions(
            name='googleuserfile',
            options={'verbose_name': 'Google User File', 'verbose_name_plural': 'Google User Files'},
        ),
    ]
