# Generated by Django 5.0 on 2025-06-24 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0003_uploadedfile_node_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleDocCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(unique=True)),
                ('last_hash', models.CharField(blank=True, max_length=128, null=True)),
                ('last_fetched', models.DateTimeField(auto_now=True)),
                ('node_id', models.CharField(blank=True, max_length=255, null=True)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gdoc_caches', to='flows.flow')),
            ],
        ),
    ]
