# Generated by Django 5.0 on 2025-07-30 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_alter_supportticket_ticket_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportticket',
            name='ticket_id',
        ),
    ]
