# Generated by Django 5.0 on 2025-07-31 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_remove_supportticket_ticket_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportticket',
            name='priority',
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], default='open', max_length=20),
        ),
        migrations.DeleteModel(
            name='SupportTicketResponse',
        ),
    ]
